package com.potatopixelartstudios.teddygame;

import android.content.Context;
import android.graphics.*;
import android.view.KeyEvent;
import android.view.MotionEvent;
import android.view.View;
import java.util.HashMap;
import java.util.Map;

/** Canvas-driven Android vertical slice: hub, platforming, combat, RPG progression and Pumpkin King boss. */
public final class GameView extends View {
    private static final float VW=1280f,VH=720f,GROUND=540f,PH=96f,GRAVITY=1550f,SPEED=330f,JUMP=-610f;
    private enum Screen{TITLE,INTRO,PLAYING,COMPLETE}
    private enum Control{LEFT,RIGHT,JUMP,ATTACK,GOLD,VIOLET,BALANCE,TALK,POTION}
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), pixel=new Paint();
    private final GameState s=new GameState();
    private final SaveManager save;
    private final AudioController audio;
    private final Map<Integer,Control> held=new HashMap<>();
    private final Map<Integer,Bitmap> images=new HashMap<>();
    private Screen screen=Screen.TITLE;
    private boolean paused,released,lanternShown,forestShown,returnShown,bossRoared;
    private long lastNs,attackUntil,magicUntil,storyUntil,hurtUntil;
    private String story="";
    private float cam;

    GameView(Context c){super(c);setFocusable(true);setFocusableInTouchMode(true);pixel.setAntiAlias(false);save=new SaveManager(c);audio=new AudioController(c);loadImages();requestFocus();}
    private void loadImages(){int[] ids={R.drawable.bg_village,R.drawable.bg_forest,R.drawable.hero_idle,R.drawable.hero_run_1,R.drawable.hero_run_2,R.drawable.hero_jump,R.drawable.hero_fall,R.drawable.hero_attack,R.drawable.hero_golden,R.drawable.hero_nightmare,R.drawable.npc_witch_guide,R.drawable.npc_ghost_child,R.drawable.npc_skeleton_blacksmith,R.drawable.npc_vampire_merchant,R.drawable.enemy_slime,R.drawable.enemy_goblin,R.drawable.enemy_living_pumpkin,R.drawable.boss_pumpkin_king,R.drawable.item_heart_shard,R.drawable.prop_quest_board,R.drawable.interactable_checkpoint,R.drawable.prop_magic_lamp,R.drawable.prop_pumpkin,R.drawable.tile_grass};for(int id:ids){Bitmap b=BitmapFactory.decodeResource(getResources(),id);if(b!=null)images.put(id,b);}}
    void resumeGame(){paused=false;lastNs=System.nanoTime();postInvalidateOnAnimation();}
    void pauseAndSave(){if(screen==Screen.PLAYING||screen==Screen.COMPLETE)save.save(s);paused=true;held.clear();}
    void release(){if(released)return;released=true;audio.release();for(Bitmap b:images.values())if(!b.isRecycled())b.recycle();images.clear();}

    @Override protected void onDraw(Canvas out){super.onDraw(out);if(released)return;long nowNs=System.nanoTime(),now=nowNs/1_000_000L;float dt=lastNs==0?0f:Math.min(.033f,(nowNs-lastNs)/1_000_000_000f);lastNs=nowNs;if(screen==Screen.PLAYING&&!paused)update(dt,now);float sc=Math.min(getWidth()/VW,getHeight()/VH),ox=(getWidth()-VW*sc)/2f,oy=(getHeight()-VH*sc)/2f;out.save();out.translate(ox,oy);out.scale(sc,sc);drawVirtual(out,now);out.restore();postInvalidateOnAnimation();}
    private void update(float dt,long now){boolean l=pressed(Control.LEFT),r=pressed(Control.RIGHT);float target=(l^r)?(l?-SPEED:SPEED):0;s.velocityX+=(target-s.velocityX)*Math.min(1f,dt*12f);if(target!=0)s.facingRight=target>0;s.playerX=clampf(s.playerX+s.velocityX*dt,20,GameState.WORLD_END_X-100);s.velocityY+=GRAVITY*dt;s.playerY+=s.velocityY*dt;if(s.playerY>=GROUND-PH){s.playerY=GROUND-PH;s.velocityY=0;s.grounded=true;s.jumpsUsed=0;}else s.grounded=false;updateEnemies(dt,now);updateBoss(dt,now);s.updateStoryProgress();s.regenerateMagic(dt);storyEvents(now);cam=clampf(s.playerX-430,0,GameState.WORLD_END_X-VW);if(s.questStage==GameState.QuestStage.COMPLETE){save.save(s);screen=Screen.COMPLETE;}}
    private void updateEnemies(float dt,long now){for(GameState.Enemy e:s.getEnemies()){if(!e.alive)continue;if(Math.abs(e.x-s.playerX)<320){e.direction=e.x<s.playerX?1:-1;e.x+=e.direction*70*dt;if(Math.abs(e.x-s.playerX)<62){s.damagePlayer(e.maxHealth>=75?15:10,now);hurtUntil=now+180;}}else{e.x+=e.direction*36*dt;if(e.x<=e.patrolLeft||e.x>=e.patrolRight)e.direction*=-1;}}}
    private void updateBoss(float dt,long now){if(!s.bossSpawned||s.bossPurified)return;if(!bossRoared){bossRoared=true;audio.play(AudioController.Cue.BOSS);card("CORRUPTED PUMPKIN KING\n\"Can't control it... RUN!\"",2300,now);}float dx=s.playerX-s.bossX;if(Math.abs(dx)>115)s.bossX+=Math.signum(dx)*92*dt;if(now-s.bossLastAttackMs>1350){s.bossLastAttackMs=now;if(Math.abs(dx)<210){s.damagePlayer(20,now);hurtUntil=now+220;audio.play(AudioController.Cue.HURT);}}}
    private void storyEvents(long now){if(s.lanternBroken&&!lanternShown){lanternShown=true;card("THE NIGHT THE LIGHT BROKE\nThe Heart Lantern shatters. Golden and violet shards tear across the sky.\nA voice whispers: \"At last.\"",3900,now);audio.play(AudioController.Cue.MAGIC);save.save(s);}if(s.questStage==GameState.QuestStage.FOREST&&!forestShown){forestShown=true;card("WHISPERING FOREST\nThese creatures are overwhelmed, not evil. Find the first Heart Shard.",3300,now);audio.play(AudioController.Cue.CHECKPOINT);save.save(s);}if(s.bossPurified&&!returnShown){returnShown=true;card("BALANCE\nGold gives chaos direction. Violet gives it force.\nThe Pumpkin King is free — bring the Heart Shard home.",4200,now);audio.play(AudioController.Cue.QUEST);save.save(s);}}
    private void card(String t,long ms,long now){story=t;storyUntil=now+ms;}

    private void drawVirtual(Canvas c,long now){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(18,12,28));c.drawRect(0,0,VW,VH,p);if(screen==Screen.TITLE)drawTitle(c);else if(screen==Screen.INTRO)drawIntro(c);else if(screen==Screen.PLAYING)drawWorld(c,now);else drawComplete(c);}
    private void drawTitle(Canvas c){background(c,R.drawable.bg_village);shade(c,190);txt(c,"TEDDY GAME",640,175,68,Color.rgb(246,205,89),true);txt(c,"2D SIDE-SCROLLING RPG ACTION-PLATFORMER",640,230,25,Color.WHITE,true);txt(c,"TWO SIDES. ONE HEART.",640,278,30,Color.rgb(205,110,235),true);sprite(c,R.drawable.hero_idle,564,315,152,152,false);button(c,440,505,840,575,save.hasSave()?"CONTINUE":"BEGIN STORY",true);if(save.hasSave())button(c,490,595,790,650,"NEW GAME",false);txt(c,"Potato Pixel Art Studios • Vertical Slice v0.1",640,690,18,Color.LTGRAY,false);}
    private void drawIntro(Canvas c){background(c,R.drawable.bg_village);shade(c,205);txt(c,"MOONSTITCH HOLLOW",640,145,42,Color.rgb(246,205,89),true);String[] a={"Between the Heartlands and Nightmare Realm stands a village where strange creatures live together.","The Heart Lantern burns with one golden flame and one violet flame — neither complete alone.","Teddy carries both powers in one stitched heart. Nightmare is chaos and instinct, not evil.","Tonight is Moonstitch Hollow's greatest Halloween celebration.","Walk right. Meet the villagers. Reach the Heart Lantern."};float y=215;for(String x:a){txt(c,x,640,y,23,Color.WHITE,false);y+=62;}button(c,470,535,810,600,"ENTER THE FESTIVAL",true);}
    private void drawWorld(Canvas c,long now){background(c,s.playerX<1900?R.drawable.bg_village:R.drawable.bg_forest);p.setColor(s.playerX<1900?Color.rgb(66,48,54):Color.rgb(48,68,48));c.drawRect(0,GROUND,VW,VH,p);Bitmap tile=images.get(R.drawable.tile_grass);if(tile!=null)for(int x=-64;x<VW+64;x+=64)c.drawBitmap(tile,null,new RectF(x,GROUND-4,x+64,GROUND+60),pixel);worldSprite(c,R.drawable.prop_quest_board,430,440,72,88);worldSprite(c,R.drawable.prop_magic_lamp,1080,395,96,128);worldSprite(c,R.drawable.interactable_checkpoint,1880,430,86,100);worldSprite(c,R.drawable.npc_ghost_child,360,432,92,96);worldSprite(c,R.drawable.npc_skeleton_blacksmith,610,428,96,100);worldSprite(c,R.drawable.npc_vampire_merchant,800,428,96,100);worldSprite(c,R.drawable.npc_witch_guide,930,426,98,102);for(GameState.Enemy e:s.getEnemies())if(e.alive){int id=e.id.equals("slime")?R.drawable.enemy_slime:e.id.equals("goblin")?R.drawable.enemy_goblin:R.drawable.enemy_living_pumpkin;worldSprite(c,id,e.x,e.y,84,84);bar(c,e.x-cam-38,e.y-24,76,7,e.health/(float)e.maxHealth,Color.rgb(224,78,92));}if(s.bossSpawned&&!s.bossPurified){worldSprite(c,R.drawable.boss_pumpkin_king,s.bossX,s.bossY-40,150,150);txt(c,"CORRUPTED PUMPKIN KING",640,92,24,Color.WHITE,true);bar(c,340,108,600,18,s.bossHealth/(float)GameState.BOSS_MAX_HEALTH,Color.rgb(208,73,93));if(s.isPurificationAvailable())txt(c,"THE KING IS OVERWHELMED — USE BALANCE",640,150,25,Color.rgb(251,219,103),true);}drawPlayer(c,now);drawHud(c);controls(c);if(paused)pausePanel(c);if(storyUntil>now)storyCard(c);}
    private void drawPlayer(Canvas c,long now){int id;if(now<attackUntil)id=R.drawable.hero_attack;else if(now<magicUntil)id=s.nightmare>=s.heartland?R.drawable.hero_nightmare:R.drawable.hero_golden;else if(!s.grounded)id=s.velocityY<0?R.drawable.hero_jump:R.drawable.hero_fall;else if(Math.abs(s.velocityX)>40)id=((now/150)%2==0)?R.drawable.hero_run_1:R.drawable.hero_run_2;else id=R.drawable.hero_idle;float x=s.playerX-cam;if(!(now<hurtUntil&&(now/60)%2==0))sprite(c,id,x-44,s.playerY-10,96,96,!s.facingRight);if(now<magicUntil){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(Color.rgb(211,94,233));c.drawCircle(x+4,s.playerY+42,63,p);p.setStyle(Paint.Style.FILL);}}
    private void drawHud(Canvas c){p.setColor(Color.argb(195,16,10,28));c.drawRoundRect(new RectF(20,18,490,140),18,18,p);txtL(c,"LV "+s.level+"  AXE +"+s.weaponLevel+"  COINS "+s.coins+"  SHARDS "+s.heartShards,40,48,19,Color.WHITE,true);bar(c,40,62,280,14,s.health/100f,Color.rgb(211,65,82));txtL(c,"HP "+s.health,330,75,17,Color.WHITE,false);bar(c,40,88,180,10,s.heartland/100f,Color.rgb(241,194,67));txtL(c,"HEARTLAND "+s.heartland,230,98,15,Color.rgb(250,220,115),true);bar(c,40,110,180,10,s.nightmare/100f,Color.rgb(160,72,199));txtL(c,"NIGHTMARE "+s.nightmare,230,120,15,Color.rgb(218,130,239),true);txtL(c,objective(),650,42,19,Color.WHITE,true);txtL(c,"XP "+s.xp+"/"+s.xpForNextLevel(),650,70,17,Color.LTGRAY,false);}
    private String objective(){switch(s.questStage){case FESTIVAL:return"QUEST: Reach the Heart Lantern";case LANTERN_BROKEN:return"QUEST: Follow the Heart Shard trail";case FOREST:return"QUEST: Cross the Whispering Forest";case BOSS:return s.isPurificationAvailable()?"QUEST: Stabilize the Pumpkin King":"QUEST: Weaken the Pumpkin King";case RETURN_HOME:return"QUEST: Bring the Heart Shard home";default:return"QUEST COMPLETE: First Heart Shard";}}
    private void controls(Canvas c){circle(c,95,620,65,"◀",Control.LEFT,Color.rgb(73,59,88));circle(c,235,620,65,"▶",Control.RIGHT,Color.rgb(73,59,88));circle(c,1120,610,62,"JUMP",Control.JUMP,Color.rgb(73,101,125));circle(c,980,620,62,"AXE",Control.ATTACK,Color.rgb(123,75,60));circle(c,1115,465,54,"GOLD",Control.GOLD,Color.rgb(173,137,50));circle(c,995,475,54,"VIOLET",Control.VIOLET,Color.rgb(112,54,139));circle(c,862,500,58,"BALANCE",Control.BALANCE,s.isPurificationAvailable()?Color.rgb(182,82,137):Color.rgb(65,51,76));circle(c,735,620,54,"TALK",Control.TALK,Color.rgb(63,92,84));circle(c,610,625,48,"POTION",Control.POTION,Color.rgb(117,59,94));button(c,1198,22,1262,72,"II",false);}
    private void pausePanel(Canvas c){shadeRect(c,260,120,1020,600,225);txt(c,"PAUSED",640,205,46,Color.rgb(246,205,89),true);txt(c,"Teddy is one person. Gold and violet are both his.",640,260,23,Color.WHITE,false);txt(c,objective(),640,330,21,Color.WHITE,true);button(c,445,420,835,485,"RESUME",true);button(c,445,505,835,565,"SAVE & TITLE",false);}
    private void storyCard(Canvas c){shadeRect(c,170,165,1110,370,225);String[] lines=story.split("\\n");float y=220;for(int i=0;i<lines.length;i++){txt(c,lines[i],640,y,i==0?30:21,i==0?Color.rgb(246,205,89):Color.WHITE,i==0);y+=i==0?55:38;}}
    private void drawComplete(Canvas c){background(c,R.drawable.bg_village);shade(c,205);sprite(c,R.drawable.item_heart_shard,570,95,140,140,false);txt(c,"FIRST HEART SHARD RESTORED",640,285,42,Color.rgb(246,205,89),true);txt(c,"The Pumpkin King was saved by Heartland focus and Nightmare force working together.",640,340,21,Color.WHITE,false);txt(c,"Moonstitch Hollow remembers what you did.",640,385,25,Color.rgb(210,118,234),true);button(c,430,500,850,570,"PLAY AGAIN FROM SAVE",true);button(c,480,590,800,648,"TITLE",false);}

    private void background(Canvas c,int id){Bitmap b=images.get(id);if(b!=null)c.drawBitmap(b,new Rect(0,0,b.getWidth(),b.getHeight()),new RectF(0,0,VW,VH),pixel);}
    private void shade(Canvas c,int a){p.setColor(Color.argb(a,15,9,24));c.drawRect(0,0,VW,VH,p);} private void shadeRect(Canvas c,float l,float t,float r,float b,int a){p.setColor(Color.argb(a,15,9,24));c.drawRoundRect(new RectF(l,t,r,b),18,18,p);}
    private void worldSprite(Canvas c,int id,float wx,float y,float w,float h){float x=wx-cam;if(x<-w||x>VW+w)return;sprite(c,id,x-w/2,y,w,h,false);} private void sprite(Canvas c,int id,float x,float y,float w,float h,boolean flip){Bitmap b=images.get(id);if(b==null)return;RectF d=new RectF(x,y,x+w,y+h);if(flip){c.save();c.scale(-1,1,x+w/2,y+h/2);c.drawBitmap(b,null,d,pixel);c.restore();}else c.drawBitmap(b,null,d,pixel);}
    private void bar(Canvas c,float x,float y,float w,float h,float q,int color){q=clampf(q,0,1);p.setColor(Color.argb(210,28,19,35));c.drawRoundRect(new RectF(x,y,x+w,y+h),h/2,h/2,p);p.setColor(color);c.drawRoundRect(new RectF(x,y,x+w*q,y+h),h/2,h/2,p);} private void txt(Canvas c,String t,float x,float y,float z,int col,boolean bold){p.setTextSize(z);p.setTextAlign(Paint.Align.CENTER);p.setColor(col);p.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);c.drawText(t,x,y,p);} private void txtL(Canvas c,String t,float x,float y,float z,int col,boolean bold){p.setTextSize(z);p.setTextAlign(Paint.Align.LEFT);p.setColor(col);p.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);c.drawText(t,x,y,p);}
    private void button(Canvas c,float l,float t,float r,float b,String text,boolean hi){p.setColor(hi?Color.rgb(111,50,142):Color.rgb(47,37,58));c.drawRoundRect(new RectF(l,t,r,b),16,16,p);txt(c,text,(l+r)/2,(t+b)/2+8,22,Color.WHITE,true);} private void circle(Canvas c,float x,float y,float rad,String text,Control ctl,int color){p.setColor(pressed(ctl)?Color.rgb(Math.min(255,Color.red(color)+38),Math.min(255,Color.green(color)+38),Math.min(255,Color.blue(color)+38)):color);c.drawCircle(x,y,rad,p);txt(c,text,x,y+7,text.length()>5?14:20,Color.WHITE,true);}

    @Override public boolean onTouchEvent(MotionEvent e){float sc=Math.min(getWidth()/VW,getHeight()/VH),ox=(getWidth()-VW*sc)/2f,oy=(getHeight()-VH*sc)/2f;int a=e.getActionMasked(),i=e.getActionIndex();if(a==MotionEvent.ACTION_CANCEL){held.clear();return true;}if(a==MotionEvent.ACTION_DOWN||a==MotionEvent.ACTION_POINTER_DOWN){handle(e.getPointerId(i),(e.getX(i)-ox)/sc,(e.getY(i)-oy)/sc);}else if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_POINTER_UP)held.remove(e.getPointerId(i));return true;}
    private void handle(int pointer,float x,float y){long now=System.currentTimeMillis();if(screen==Screen.TITLE){if(y>=495&&y<=585){if(save.hasSave()){save.loadInto(s);syncFlags();screen=Screen.PLAYING;}else screen=Screen.INTRO;}else if(save.hasSave()&&y>=585){save.clear();newGame();screen=Screen.INTRO;}return;}if(screen==Screen.INTRO){if(y>=510){newGame();screen=Screen.PLAYING;card("HALLOWEEN FESTIVAL\nGhost Child: \"Does it ever feel strange? Being both?\"\nTeddy: \"Does being see-through feel strange?\"",4200,now);}return;}if(screen==Screen.COMPLETE){if(y>=485&&y<=585){screen=Screen.PLAYING;s.playerX=1720;}else if(y>=580)screen=Screen.TITLE;return;}if(paused){if(y>=400&&y<=500)paused=false;else if(y>=500&&y<=590){save.save(s);screen=Screen.TITLE;paused=false;}return;}if(x>=1180&&y<=90){paused=true;save.save(s);return;}Control k=controlAt(x,y);if(k==null)return;if(k==Control.LEFT||k==Control.RIGHT){held.put(pointer,k);return;}if(k==Control.JUMP){jump();return;}if(k==Control.ATTACK){attack(now);return;}if(k==Control.GOLD){if(s.useHeartland()){magicUntil=now+380;audio.play(AudioController.Cue.HEAL);}return;}if(k==Control.VIOLET){s.useNightmareBurst();magicUntil=now+420;audio.play(AudioController.Cue.MAGIC);return;}if(k==Control.BALANCE){if(s.purifyBoss()){magicUntil=now+850;save.save(s);}else card("BALANCE NEEDS BOTH POWERS\nWeaken the Pumpkin King and keep at least 35 Heartland + 35 Nightmare.",2300,now);return;}if(k==Control.TALK){interact(now);return;}if(k==Control.POTION&&s.usePotion())audio.play(AudioController.Cue.HEAL);}
    private Control controlAt(float x,float y){if(dist(x,y,95,620)<=78)return Control.LEFT;if(dist(x,y,235,620)<=78)return Control.RIGHT;if(dist(x,y,1120,610)<=75)return Control.JUMP;if(dist(x,y,980,620)<=75)return Control.ATTACK;if(dist(x,y,1115,465)<=66)return Control.GOLD;if(dist(x,y,995,475)<=66)return Control.VIOLET;if(dist(x,y,862,500)<=70)return Control.BALANCE;if(dist(x,y,735,620)<=66)return Control.TALK;if(dist(x,y,610,625)<=60)return Control.POTION;return null;}
    private void jump(){if(s.grounded||s.jumpsUsed<2){s.velocityY=s.jumpsUsed==0?JUMP:JUMP*.88f;s.grounded=false;s.jumpsUsed++;audio.play(AudioController.Cue.JUMP);}}
    private void attack(long now){if(now-s.lastAttackMs<260)return;s.lastAttackMs=now;attackUntil=now+210;audio.play(AudioController.Cue.ATTACK);int hits=s.performPlayerAttack(75);if(s.bossSpawned&&!s.bossPurified){float f=s.playerX+(s.facingRight?70:-70);if(Math.abs(s.bossX-f)<125){s.damageBoss(20+s.weaponLevel*3);hits++;}}if(hits>0)audio.play(AudioController.Cue.HIT);}
    private void interact(long now){if(Math.abs(s.playerX-360)<135){card("GHOST CHILD\n\"Whatever happens, come back.\"",2300,now);return;}if(Math.abs(s.playerX-610)<135){int cost=s.weaponLevel*15;if(s.buyAxeUpgrade()){card("SKELETON BLACKSMITH\nAxe upgraded. \"Try not to break this one, Teddy.\"",2200,now);save.save(s);}else card("SKELETON BLACKSMITH\nUpgrade costs "+cost+" coins. You have "+s.coins+".",2200,now);return;}if(Math.abs(s.playerX-800)<135){if(s.coins>=8){s.coins-=8;s.potions++;card("VAMPIRE MERCHANT\nPotion purchased. \"An absolute bargain. For me.\"",2200,now);save.save(s);}else card("VAMPIRE MERCHANT\nPotion: 8 coins. No sunlight accepted.",2200,now);return;}if(Math.abs(s.playerX-930)<140){card("WITCH GUIDE\n\"The Lantern holds two flames. Neither survives alone.\"",2800,now);return;}card("No one nearby needs Teddy's help right now.",1500,now);}
    private void newGame(){s.playerX=220;s.playerY=GROUND-PH;s.velocityX=s.velocityY=0;s.health=100;s.heartland=s.nightmare=50;s.xp=0;s.level=1;s.coins=10;s.weaponLevel=1;s.potions=1;s.heartShards=0;s.questStage=GameState.QuestStage.FESTIVAL;s.lanternBroken=s.bossSpawned=s.bossPurified=s.checkpointActivated=s.villageReturned=false;s.bossHealth=GameState.BOSS_MAX_HEALTH;s.bossX=4050;s.resetEnemies();lanternShown=forestShown=returnShown=bossRoared=false;cam=0;}
    private void syncFlags(){lanternShown=s.lanternBroken;forestShown=s.questStage.ordinal()>=GameState.QuestStage.FOREST.ordinal();returnShown=s.bossPurified;bossRoared=s.bossSpawned||s.bossPurified;}
    private boolean pressed(Control c){return held.containsValue(c);} private static float dist(float a,float b,float c,float d){float x=a-c,y=b-d;return(float)Math.sqrt(x*x+y*y);} private static float clampf(float v,float a,float b){return Math.max(a,Math.min(b,v));}
    @Override public boolean onKeyDown(int key,KeyEvent e){if(screen!=Screen.PLAYING)return super.onKeyDown(key,e);if(key==KeyEvent.KEYCODE_DPAD_LEFT||key==KeyEvent.KEYCODE_A)held.put(-1,Control.LEFT);else if(key==KeyEvent.KEYCODE_DPAD_RIGHT||key==KeyEvent.KEYCODE_D)held.put(-2,Control.RIGHT);else if(key==KeyEvent.KEYCODE_SPACE||key==KeyEvent.KEYCODE_BUTTON_A)jump();else if(key==KeyEvent.KEYCODE_J||key==KeyEvent.KEYCODE_BUTTON_X)attack(System.currentTimeMillis());else if(key==KeyEvent.KEYCODE_H)s.useHeartland();else if(key==KeyEvent.KEYCODE_N)s.useNightmareBurst();else if(key==KeyEvent.KEYCODE_B)s.purifyBoss();else if(key==KeyEvent.KEYCODE_E||key==KeyEvent.KEYCODE_BUTTON_Y)interact(System.currentTimeMillis());else if(key==KeyEvent.KEYCODE_ESCAPE||key==KeyEvent.KEYCODE_BUTTON_START)paused=!paused;return true;}
    @Override public boolean onKeyUp(int key,KeyEvent e){if(key==KeyEvent.KEYCODE_DPAD_LEFT||key==KeyEvent.KEYCODE_A)held.remove(-1);if(key==KeyEvent.KEYCODE_DPAD_RIGHT||key==KeyEvent.KEYCODE_D)held.remove(-2);return true;}
}
